# Generated by Django 3.0.5 on 2020-04-20 05:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('load_text', models.TextField(verbose_name='サブ')),
                ('main_text', models.TextField(verbose_name='メイン')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成した日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sblog.Category', verbose_name='カテゴリ')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
